config/routes.rb
Rentalpayment::Application.routes.draw do
  resources :leases

  resources :properties

  resources :roles

  devise_for :users

  resources :property_types

  resources :salutations

  resources :people
  
  resources :rights

  
  root :to => "home#index"
  

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :person
  belongs_to :property_type
  
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  
  validates :property_type, :description, presence: true
  
  validates :display_order, numericality: {greater_than_or_equal_to: 1}
  
  has_many :properties
  
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :ok }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_name %><br />
    <%= f.text_field :property_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address_line_1 %><br />
    <%= f.text_field :address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :address_line_2 %><br />
    <%= f.text_field :address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :province_or_state %><br />
    <%= f.text_field :province_or_state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :number_of_units %><br />
    <%= f.number_field :number_of_units %>
  </div>
  <div class="field">
    <%= f.label :property_type_id %><br />
    <%= f.select :property_type_id, PropertyType.all.collect {|pt| [pt.property_type, pt.id]} %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.select :person_id, Person.all.collect {|p| [p.display_name, p.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Property name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Number of units</th>
    <th>Type</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.property_name %></td>
    <td><%= property.description %></td>
    <td><%= render  :partial => "shared/formatted_address", :locals => {:address=>property} %></td>
    <td><%= property.number_of_units %></td>
    <td><%= property.property_type.property_type%></td>
    <td><%= property.person.display_name%></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Property name:</b>
  <%= @property.property_name %>
</p>

<p>
  <b>Description:</b>
  <%= @property.description %>
</p>

<p>
  <b>Address line 1:</b>
  <%= @property.address_line_1 %>
</p>

<p>
  <b>Address line 2:</b>
  <%= @property.address_line_2 %>
</p>

<p>
  <b>City:</b>
  <%= @property.city %>
</p>

<p>
  <b>Province or state:</b>
  <%= @property.province_or_state %>
</p>

<p>
  <b>Country:</b>
  <%= @property.country %>
</p>

<p>
  <b>Postal code:</b>
  <%= @property.postal_code %>
</p>

<p>
  <b>Number of units:</b>
  <%= @property.number_of_units %>
</p>

<p>
  <b>Person:</b>
  <%= @property.person_id %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>