config/routes.rb
Rentalpayment::Application.routes.draw do
  resources :leases

  resources :properties

  resources :roles

  devise_for :users

  resources :property_types

  resources :salutations

  resources :people
  
  resources :rights

  
  root :to => "home#index"
  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/grant.rb
class Grant < ActiveRecord::Base
  belongs_to :role
  belongs_to :right
end

app/models/lease.rb
class Lease < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  
  COUNTRIES = ['Canada', 'U.S.A.', 'Mexico']
  PROVINCES = {'Canada' => ['Alberta', 'B.C.', 'Saskatchewan'], 
    'U.S.A.' => ['Washington', 'Idaho', 'Montana'], 
    'Mexico' => ['D.F.']}
    
  belongs_to :salutation
  
  validates :province_or_state, province: true
  
  validates :email, :first_name, :last_name, :city, :postal_code, presence: true
  
  validates :country, inclusion: COUNTRIES
  
  validates :email, email:  true
  
  has_many :properties
  
  def display_name 
    "#{first_name} #{last_name}"
  end
  
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :person
  belongs_to :property_type
  
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  
  validates :property_type, :description, presence: true
  
  validates :display_order, numericality: {greater_than_or_equal_to: 1}
  
  has_many :properties
  
end

app/models/right.rb
class Right < ActiveRecord::Base
  has_many :grants
  has_many :roles, :through => :grants
  
  
  OPERATIONS_MAPPINGS = {
    "new" => "CREATE",
    "create" => "CREATE",
    "edit" => "UPDATE",
    "update" => "UPDATE",
    "destroy" => "DELETE",
    "show" => "READ",
    "index" => "READ",
  }
  
  validates :resource, :operation, presence: true
  
  validates :operation, inclusion: OPERATIONS_MAPPINGS.values

end

app/models/role.rb
class Role < ActiveRecord::Base
  
  has_many :grants
  has_many :assignments
  has_many :users, :through => :assignments
  has_many :rights, :through => :grants
  validates :role_name, :description,  presence: true
  
  
  scope :for, lambda { |action, resource|
    where("rights.operation = ? AND rights.resource = ?",
    Right::OPERATIONS_MAPPINGS[action],resource) }
  
  def admin?
    role_name == 'Administrator'
  end
  
end

app/models/salutation.rb
class Salutation < ActiveRecord::Base
  has_many :people
  before_destroy :ensure_not_referenced_by_any_person

  LANGUAGES = ['en', 'fr', 'es']
  
  validates :salutation, presence: true
  validates :language, inclusion: Salutation::LANGUAGES
  validates :display_order, numericality: {greater_than_or_equal_to: 1}
  
  def self.salutations_for_select(lang='en')
    Salutation.find_all_by_language(lang).collect {|s| [s.salutation, s.id] }
  end
  
  private

   def ensure_not_referenced_by_any_person
     
    return true if people.empty?
    errors.add(:base, 'People are using this salutation')
    return false
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :assignments
  has_many :roles, :through => :assignments

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def authorized_for?(action, resource)
    roles.includes(:rights).for(action, resource).any? or roles.any? {|rl| rl.admin?}
  end
  
  def in_role?(rolename)
    roles.any? {|rl| rl.admin? or rl.role_name == rolename}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  skip_before_filter  :authenticate_user!
  skip_before_filter :check_auth
  def index
  end
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
 
  # GET /property_types
  # GET /property_types.json
  def index
    @property_types = PropertyType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @property_types }
    end
  end

  # GET /property_types/1
  # GET /property_types/1.json
  def show
    @property_type = PropertyType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property_type }
    end
  end

  # GET /property_types/new
  # GET /property_types/new.json
  def new
    @property_type = PropertyType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property_type }
    end
  end

  # GET /property_types/1/edit
  def edit
    @property_type = PropertyType.find(params[:id])
  end

  # POST /property_types
  # POST /property_types.json
  def create
    @property_type = PropertyType.new(params[:property_type])

    respond_to do |format|
      if @property_type.save
        format.html { redirect_to @property_type, notice: 'Property type was successfully created.' }
        format.json { render json: @property_type, status: :created, location: @property_type }
      else
        format.html { render action: "new" }
        format.json { render json: @property_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /property_types/1
  # PUT /property_types/1.json
  def update
    @property_type = PropertyType.find(params[:id])

    respond_to do |format|
      if @property_type.update_attributes(params[:property_type])
        format.html { redirect_to @property_type, notice: 'Property type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @property_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_types/1
  # DELETE /property_types/1.json
  def destroy
    @property_type = PropertyType.find(params[:id])
    @property_type.destroy

    respond_to do |format|
      format.html { redirect_to property_types_url }
      format.json { head :ok }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
 
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/property_types_helper.rb
module PropertyTypesHelper
end

app/helpers/rights_helper.rb
module RightsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/salutations_helper.rb
module SalutationsHelper
end

app/views/property_types/_form.html.erb
<%= form_for(@property_type) do |f| %>
  <% if @property_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property_type.errors.count, "error") %> prohibited this property_type from being saved:</h2>

      <ul>
      <% @property_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_type %><br />
    <%= f.text_field :property_type, width: 50 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 4, width:50 %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br />
    <%= f.number_field :display_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/property_types/edit.html.erb
<h1>Editing property_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @property_type %> |
<%= link_to 'Back', property_types_path %>

app/views/property_types/index.html.erb
<h1>Listing property_types</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Description</th>
    <th>Display order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @property_types.each do |property_type| %>
  <tr>
    <td><%= property_type.property_type %></td>
    <td><%= property_type.description %></td>
    <td><%= property_type.display_order %></td>
    <td><%= link_to 'Show', property_type %></td>
    <td><%= link_to 'Edit', edit_property_type_path(property_type) %></td>
    <td><%= link_to 'Destroy', property_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property type', new_property_type_path %>

app/views/property_types/new.html.erb
<h1>New property_type</h1>

<%= render 'form' %>

<%= link_to 'Back', property_types_path %>

app/views/property_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @property_type.property_type %>
</p>

<p>
  <b>Description:</b>
  <%= @property_type.description %>
</p>

<p>
  <b>Display order:</b>
  <%= @property_type.display_order %>
</p>


<%= link_to 'Edit', edit_property_type_path(@property_type) %> |
<%= link_to 'Back', property_types_path %>