config/routes.rb
Rentalpayment::Application.routes.draw do
  resources :leases

  resources :properties

  resources :roles

  devise_for :users

  resources :property_types

  resources :salutations

  resources :people
  
  resources :rights

  
  root :to => "home#index"
  

end

app/models/right.rb
class Right < ActiveRecord::Base
  has_many :grants
  has_many :roles, :through => :grants
  
  
  OPERATIONS_MAPPINGS = {
    "new" => "CREATE",
    "create" => "CREATE",
    "edit" => "UPDATE",
    "update" => "UPDATE",
    "destroy" => "DELETE",
    "show" => "READ",
    "index" => "READ",
  }
  
  validates :resource, :operation, presence: true
  
  validates :operation, inclusion: OPERATIONS_MAPPINGS.values

end

app/controllers/rights_controller.rb
class RightsController < ApplicationController
  # GET /rights
  # GET /rights.json
  def index
    @rights = Right.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rights }
    end
  end

  # GET /rights/1
  # GET /rights/1.json
  def show
    @right = Right.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @right }
    end
  end

  # GET /rights/new
  # GET /rights/new.json
  def new
    @right = Right.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @right }
    end
  end

  # GET /rights/1/edit
  def edit
    @right = Right.find(params[:id])
  end

  # POST /rights
  # POST /rights.json
  def create
    @right = Right.new(params[:right])

    respond_to do |format|
      if @right.save
        format.html { redirect_to @right, notice: 'Right was successfully created.' }
        format.json { render json: @right, status: :created, location: @right }
      else
        format.html { render action: "new" }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rights/1
  # PUT /rights/1.json
  def update
    @right = Right.find(params[:id])

    respond_to do |format|
      if @right.update_attributes(params[:right])
        format.html { redirect_to @right, notice: 'Right was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rights/1
  # DELETE /rights/1.json
  def destroy
    @right = Right.find(params[:id])
    @right.destroy

    respond_to do |format|
      format.html { redirect_to rights_url }
      format.json { head :ok }
    end
  end
end

app/helpers/rights_helper.rb
module RightsHelper
end

app/views/rights/_form.html.erb
<%= form_for(@right) do |f| %>
  <% if @right.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@right.errors.count, "error") %> prohibited this right from being saved:</h2>

      <ul>
      <% @right.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
     <%= f.label :resource %><br />
     <%= f.text_field :resource %>
   </div>
   <div class="field">
     <%= f.label :operation %><br />
     <%= f.select :operation, Right::OPERATIONS_MAPPINGS.values %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rights/edit.html.erb
<h1>Editing right</h1>

<%= render 'form' %>

<%= link_to 'Show', @right %> |
<%= link_to 'Back', rights_path %>

app/views/rights/index.html.erb
<h1>Listing rights</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rights.each do |right| %>
  <tr>
    <td><%= right.resource %></td>
    <td><%= right.operation %></td>
    <td><%= link_to 'Show', right %></td>
    <td><%= link_to 'Edit', edit_right_path(right) %></td>
    <td><%= link_to 'Destroy', right, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Right', new_right_path %>

app/views/rights/new.html.erb
<h1>New right</h1>

<%= render 'form' %>

<%= link_to 'Back', rights_path %>

app/views/rights/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_right_path(@right) %> |
<%= link_to 'Back', rights_path %>